spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/concurrency?serverTimezone=UTC&characterEncoding=utf84&useSSL=false&useUnicode=true
    username: root
    password: A708
